### ISSUE TITLE
`ob init` fails when git option `branch.master.merge` is set

### ISSUE THREAD

**Issue by tek** [obsidiansystems/obelisk#792] opened 2020-07-23 21:54 UTC
Given a `~/.gitconfig` with:

```
[branch master]
merge = master
```

`ob init` fails with:

```
⇾ Setting up obelisk ✔ Built on /tmp/ob-init-e94f341ff0615220/.obelisk/impl [command]
Running 'thunk pack /tmp/ob-init-e94f341ff0615220/.obelisk/impl' with /nix/store/gd99xxp41i5dllhpx341rxscgbyzlpqn-obelisk-command-0.8.0.0/bin/ob
Creating process: /nix/store/gd99xxp41i5dllhpx341rxscgbyzlpqn-obelisk-command-0.8.0.0/bin/ob --no-handoff thunk pack /tmp/ob-init-e94f341ff0615220/.obelisk/impl
Alert: thunk pack: Certain branches in the thunk have no upstream branch set. This means we don't know to check whether all your work is saved. The offending branches are:
 
master
 
To fix this, you probably want to do:
 
git push -u origin master
 
These will push the branches to the default remote under the same name, and (thanks to the `-u`) remember that choice so you don't get this error again.
```

**Comment by 3noch** [comment] 2020-07-23 22:10
Thanks for the report!

**Comment by plt-amy** [comment] 2022-08-17 21:55
Hi! Sorry that this took so long to get around to. The issue is that, when `branch.master.merge` is set, `git for-each-ref` will not print the upstream tracking information that we need to determine whether the thunk is clean. The PR I just linked fixes that in nix-thunk, which is where our thunk implementation now lives.

While that isn't merged, the issue can be worked around by fetching an Obelisk branch that does not have a corresponding `branch.<name>.merge` set, e.g.:

```
ob init --branch develop
```

**Closed** 2022-08-18 21:16 UTC
Labels: bug, good first issue
