### ISSUE TITLE
obelisk could recompile frontend/src-bin

### ISSUE THREAD

**Issue by meditans** [obsidiansystems/obelisk#311] opened 2018-11-14 11:20 UTC
When modifying the code in ```frontend/src-bin/main.hs``` from the obelisk skeleton, the commands `ob run` and `ob watch` don't seem to pick up on the changes (in fact I don't know how I would force obelisk to run the file I wrote). Why does this happen? Does obelisk cache some files and recompile others?

**Comment by hSloan** [comment] 2018-11-26 21:33
@meditans `ob run` and `ob watch` both invoke ghci in the same way, without loading src-bin. 

As a gross alternative, you can `nix-shell -A shells.ghc` followed by `ghcid -c "cabal new-repl exe:frontend"`. The downside to this will ONLY include modules from the listed executable stanza.

**Comment by matthewbauer** [comment] 2019-11-26 17:46
Closing as a duplicate of #50. Feel free to reopen if this is still relevant.

**Closed by matthewbauer** 2019-11-26 17:46 UTC
Labels: duplicate
