### ISSUE TITLE
ghcide integration ?

### ISSUE THREAD

**Issue by JosephLucas** [obsidiansystems/obelisk#660] opened 2020-02-18 21:51 UTC
Hi, 
Thank you for developing this great obelisk framework, I am found of the overall structure.
After creating a new project with `obelisk init` what can I do to start VScode with ghcide features ?
VSCode + ghcide works well for projects created with `stack new` but with obelisk projects it seems that imported modules cannot be found. I saw the [reflex-ghcide](https://github.com/mpickering/reflex-ghcide) tool but I cannot find out how to use it properly.
Cheers

-----
Edit : Author of `reflex-ghcide` explained that his project has nothing to do with obelisk projects and ghcide.

**Comment by 3noch** [comment] 2020-02-18 22:39
Great idea! We'd love to have *some* sort of real IDE support. It's been difficult to justify investing heavily in any one idea since they tend to shift so much, but things seem to be on a good trajectory with ghcide and hie joining forces. Adding support for ghcide shouldn't be *that* hard. If you want to give it a stab I can provide pointers. Otherwise, we hope to revisit this idea but I can't say when.

**Comment by JosephLucas** [comment] 2020-02-18 23:02
Thanks. I will focus on learning and using the obelisk ecosystem first. If one day I get enough knowledge about it, I might develop tools for it :wink:

**Comment by 3noch** [comment] 2020-02-18 23:08
Keep the ideas coming!

**Comment by meditans** [comment] 2020-02-21 16:43
@JosephLucas if you want to thinker around, take a look at https://github.com/mpickering/hie-bios/issues/54 for how I got to use ghcide with obelisk skeleton. Unfortunately ghcide can't follow definitions across packages, so the usefulness is less than I originally expected, and I got back to using `ob watch` till things mature a bit

**Comment by JosephLucas** [comment] 2020-02-21 18:05
> ghcide can't follow definitions across packages

[An issue is now open for this feature](https://github.com/digital-asset/ghcide/issues/448#issuecomment-589760022).

**Comment by mpickering** [comment] 2020-02-22 12:17
`reflex-ghcide` is nothing to do with obelisk projects and ghcide. @meditans has pointed out that there previously was support in `hie-bios` for obelisk projects but seeing as nobody was using it and maintaining it, I removed it.

**Comment by JosephLucas** [comment] 2020-02-22 20:31
Ooops. So IIUC reflex-ghcide uses reflex to run itself but is not meant to handle reflex projects.

**Comment by maralorn** [comment] 2020-03-04 02:01
You can use `ghcide` with obelisk but you have to compile ghcide with the patched ghc used by obelisk. (Thanks to @mpickering for pointing that out to me.)

Steps:

1a) Compile ghcide with e.g. `cabal new-install ghcide`

1b) Alternatively since you probably don‘t want 1a) and actually want to have a nixderivation for ghcide use this (obviously terrible and brittle) code in your `default.nix` as part of the attrset passed to the `project` function.:
```nix
  shellToolOverrides = ghc: super: {
    ghcide = pkgs.haskell.lib.dontCheck ((ghc.override {
      overrides = ghc: super: {
        lsp-test =
          pkgs.haskell.lib.dontCheck (ghc.callHackage "lsp-test" "0.6.1.0" { });
        haddock-library = pkgs.haskell.lib.dontCheck
          (ghc.callHackage "haddock-library" "1.8.0" { });
        haskell-lsp = pkgs.haskell.lib.dontCheck
          (ghc.callHackage "haskell-lsp" "0.19.0.0" { });
        haskell-lsp-types = pkgs.haskell.lib.dontCheck
          (ghc.callHackage "haskell-lsp-types" "0.19.0.0" { });
        regex-posix = pkgs.haskell.lib.dontCheck
          (ghc.callHackage "regex-posix" "0.96.0.0" { });
        test-framework = pkgs.haskell.lib.dontCheck
          (ghc.callHackage "test-framework" "0.8.2.0" { });
        regex-base = pkgs.haskell.lib.dontCheck
          (ghc.callHackage "regex-base" "0.94.0.0" { });
        regex-tdfa = pkgs.haskell.lib.dontCheck
          (ghc.callHackage "regex-tdfa" "1.3.1.0" { });
        shake =
          pkgs.haskell.lib.dontCheck (ghc.callHackage "shake" "0.18.4" { });
        hie-bios = pkgs.haskell.lib.dontCheck (ghc.callHackageDirect {
          pkg = "hie-bios";
          ver = "0.4.0";
          sha256 = "19lpg9ymd9656cy17vna8wr1hvzfal94gpm2d3xpnw1d5qr37z7x";
        } { });
      };
    }).callCabal2nix "ghcide" (pkgs.fetchFromGitHub {
      owner = "digital-asset";
      repo = "ghcide";
      rev = "v0.1.0";
      sha256 = "1kf71iix46hvyxviimrcv7kvsj67hcnnqlpdsmazmlmybf7wbqbb";
    }) { });
  };
```
(Haskell dependency management in nixpkgs is terrible by design. This code will work as long as obelisk doesn‘t bump the pinned nixpkgs.)

2) Make `hie.yaml` files: e.g. in backend with
```yaml
cradle: { cabal: { component: "backend" } }
```

3) Enter `ob shell` (if you did 1b. if you did 1a just make sure `.cabal/bin` is in your PATH)

4) Run `ghcide` inside the `backend` folder to test the setup.

5) Start the editor of your choice with a ghcide plugin.

PS: Maybe we wanna integrate the above nix-expression in the obelisk repo and just give an `ghcideEnable` flag? Managing the terrible cabal version bingo should probably only be done once on the upstream.

**Comment by 3noch** [comment] 2020-03-04 03:49
Thank you so much! I ran into this myself when trying to integrate this. I will see where I can take this. :D

**Comment by 3noch** [comment] 2020-03-04 06:34
@maralorn I hope to implement your overrides in obelisk itself in #663

**Comment by mpickering** [comment] 2020-03-19 16:43
@maralorn @3noch Perhaps one of you is interested in testing the first implementation of multi-component support. Your feedback will be very valuable to me.

https://github.com/mpickering/ghcide/tree/wip/multi-rebase

**Comment by 3noch** [comment] 2020-03-19 17:51
Wow that's awesome. The current integration path in #663 uses obelisk's preprocessor to get multicomponent support in the same session, but it has some rough edges that are hard to sand down. I'll try a new branch that instead tries to rely on multi-component support!

**Comment by maralorn** [comment] 2020-05-06 17:00
@3noch ghcide is now fixed on nixpkgs-20.03 and will very soon also be fixed on nixpkgs-unstable (already merged to the haskell-updates) branch.

So when you update r-p and obelisk to newest nixpkgs you can throwaway all those weird overrides.
Of course that‘s just ghcide 0.1.0 as released to hackage. But I guess overriding it to a newer version, if needed, will now be easier than before.

I am keeping an eye on ghcide in nixpkgs, so I hope supporting ghcide this way will be reliable for a while.

After realizing how troublesome the haskell.nix variant can be, I think this is the best solution.

**Comment by 3noch** [comment] 2020-05-06 17:26
Thanks for the update! @maralorn

**Comment by 3noch** [comment] 2020-05-06 17:27
I just realized this ticket can now be closed because we have *a* story for this.

**Closed by 3noch** 2020-05-06 17:27 UTC
Labels: enhancement, user experience
