### ISSUE TITLE
prerender and CORS preflight check

### ISSUE THREAD

**Issue by janat08** [obsidiansystems/obelisk#468] opened 2019-06-30 08:19 UTC
After adding prerender_, the CORS preflight check errors began appearing. I would rather not have to disable CORS checks. I presume to be not an outlier.

**Comment by ohri-anurag** [comment] 2022-05-03 09:59
@janat08 Can you provide more details around this issue? It would help us a lot if could detail the steps to reproduce the issue.

**Comment by janat08** [comment] 2022-05-03 11:53
I might have been working in cloud ide to trigger cors, as they proxy local host.

**Comment by ohri-anurag** [comment] 2022-05-04 10:53
Closing due to lack of reproducible steps.

**Closed by ohri-anurag** 2022-05-04 10:53 UTC
Labels: bug, Medium Severity

**Comment by ohri-anurag** [comment] 2022-05-04 12:06
@janat08 In case you feel that this is still an issue, do let us know. We'll be more than happy to investigate.
