### ISSUE TITLE
`ob init` followed by `ob run` is broken due to dead link

### ISSUE THREAD

**Issue by mpickering** [obsidiansystems/obelisk#797] opened 2020-08-19 17:14 UTC
```
[matt@nixos:~/charles-ccc]$ ob run
./.obelisk/impl: command not cached, building ...
✔ Built on ./.obelisk/impl [command]
building '/nix/store/g3h6h7b8a4xncf65iwbx1wn2hpas81k5-source.drv'...

trying https://bitbucket.org/wuzzeb/webdriver-utils/get/a8b15525a1cceb0ddc47cfd4d7ab5a29fdbe3127.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 403
error: cannot download source from any mirror
builder for '/nix/store/g3h6h7b8a4xncf65iwbx1wn2hpas81k5-source.drv' failed with exit code 1
cannot build derivation '/nix/store/sr7s7lb8s4wbxlyw8zs1p3lqfnpww3h8-cabal2nix-hspec-webdriver.drv': 1 dependencies couldn't be built
error: build of '/nix/store/sr7s7lb8s4wbxlyw8zs1p3lqfnpww3h8-cabal2nix-hspec-webdriver.drv' failed
(use '--show-trace' to show detailed location information)
```

**Comment by 3noch** [comment] 2020-08-19 17:21
Eesh that's no good. Thanks.

**Comment by bxrt** [comment] 2020-10-08 21:50
@mpickering, is this still an issue? I can't reproduce it on macOS. Your last comment suggests that you solved it by correctly setting up the nix caches. If so, you should consider closing the issue.

**Comment by mpickering** [comment] 2020-10-09 16:54
@bxrt This is still an issue, as you shouldn't need to configure the caches for the derivation to work.

**Comment by ali-abrar** [comment] 2020-11-11 18:05
Should be fixed when this gets merged: https://github.com/reflex-frp/reflex-platform/pull/687

**Comment by ohri-anurag** [comment] 2022-05-03 07:13
With the latest Obelisk commit e3ec75f6988eed47189dd20f8c8514748b33ea81, the commands `ob init` and `ob run` work fine when run one after the other.

@mpickering Can you provide more details around reproducing the issue?

**Comment by ohri-anurag** [comment] 2022-05-04 10:54
The related issue has been marked as fixed, closing this one too. Could not figure out how to trigger the issue.

**Closed by ohri-anurag** 2022-05-04 10:54 UTC
Labels: bug
