### ISSUE TITLE
Could not deduce: DomBuilderSpace m ~ GhcjsDomSpace

### ISSUE THREAD

**Issue by tshinohara** [obsidiansystems/obelisk#239] opened 2018-10-11 05:09 UTC
Adding just `_ <- textInput def` to the skelton code causes error `Could not deduce: DomBuilderSpace m ~ GhcjsDomSpace`. I think it worked before `routes` branch merged to `master`.

```haskell
  , _frontend_body = do
      text "Welcome to Obelisk!"
      el "p" $ text $ T.pack commonStuff
      _a <- textInput def  -- Added this line
      elAttr "img" ("src" =: static @"obelisk.jpg") blank
```
```
frontend/src/Frontend.hs:21:13-25: error:
    • Could not deduce: DomBuilderSpace m ~ GhcjsDomSpace
        arising from a use of ‘textInput’
      from the context: ObeliskWidget t x (R FrontendRoute) m
        bound by a type expected by the context:
                   forall t (m :: * -> *) x.
                   ObeliskWidget t x (R FrontendRoute) m =>
                   Obelisk.Route.Frontend.RoutedT t (R FrontendRoute) m ()
        at frontend/src/Frontend.hs:(16,12)-(23,3)
    • In a stmt of a 'do' block: _a <- textInput def
      In the ‘_frontend_body’ field of a record
      In the expression:
        Frontend
          {_frontend_head = el "title" $ text "Obelisk Minimal Example",
           _frontend_body = do text "Welcome to Obelisk!"
                               el "p" $ text $ T.pack commonStuff
                               _a <- textInput def
                               ....}
   |
21 |       _a <- textInput def
   |             ^^^^^^^^^^^^^
```

**Comment by ElvishJerricco** [comment] 2018-10-11 09:55
I think the issue is that you're not using the result at all, so it doesn't know for sure what type you meant to use. If you bind that to a variable and actually use it for something it ought to work. Or you could give it a type explicitly.

If that is in fact the issue, this can likely also be fixed by adding a functional dependency to whatever type class is in use here. We've got a similar problem with `domEvent`, where it doesn't know which timeline type to use for the resulting event unless you actually use the event or give it an explicit type. [This PR](https://github.com/reflex-frp/reflex-dom/pull/225) fixes that case, so we could probably do something similar for this one.

**Comment by ryantrinkle** [comment] 2018-10-11 13:35
Now that routes is merged, `obelisk` will prerender your app on the server side by default.  This makes loading much snappier, but it also means you can't globally assume JS is present.  There are two solutions here:

1. The `prerender` function will give you a context in which JS is present, by taking two arguments: a widget to render server-side, and a different widget to render client-side.  The client-side widget can assume JS is available.
2. Instead of textInput (which only requires JS for historical reasons), use inputElement.  That will probably work nicely in this situation, but won't help if you are really using JS (e.g. embedding a google map, etc.)

**Closed by ryantrinkle** 2018-10-11 13:35 UTC

**Comment by ryantrinkle** [comment] 2018-10-11 15:06
@tshinohara Building HTML, CSS, etc. all work on server side - if you disable JS in your browser, the initial load should look identical to the app (but won't have any interactive behavior).  It's just things that use actual JS that won't work.

**Comment by tshinohara** [comment] 2018-10-11 15:39
@ryantrinkle Thanks for your explanation.
